# filepath: d:\Astaga Ngoding\Github\Re.Grant-Research-Grants-for-Academics\docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: ${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID}
        NEXT_PUBLIC_XELLAR_APP_ID: ${NEXT_PUBLIC_XELLAR_APP_ID}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://backend:8000/api} # Updated port
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next # Add this to prevent host .next from overwriting container's .next in dev
    depends_on:
      - backend
    # The command will be overridden in docker-compose.override.yml for development

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000" # Corrected port based on your Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgres://user:password@database:5432/regrant
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=8000 # Corrected port
    # The command will be overridden in docker-compose.override.yml for development

  database:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=regrant

volumes:
  postgres_data: