[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = "0.8.24" # Or your preferred latest compatible version
optimizer = true
optimizer_runs = 200
via_ir = true

# RPC endpoint for Lisk Sepolia Testnet
# This can be used by `forge script` and `cast` commands.
# The official public RPC is: https://rpc.sepolia-api.lisk.com
# Foundry's `rpc_endpoints` expects a TOML table.
[rpc_endpoints]
lisk_sepolia = "https://rpc.sepolia-api.lisk.com"

# For contract verification on Lisk Sepolia's Blockscout:
# Blockscout URL: https://sepolia-blockscout.lisk.com/
# Chain ID: 4202
# The verification process might be manual or via a Blockscout-compatible API.
# If an API key is needed and supported by Foundry's Etherscan plugin for Blockscout:
# [etherscan]
#   lisk_sepolia = { key = "${LISKSCAN_API_KEY_PLACEHOLDER}", url = "https://sepolia-blockscout.lisk.com/api" }
# You would then add LISKSCAN_API_KEY_PLACEHOLDER to your .env file.
# For now, we'll assume manual verification or investigate Blockscout API compatibility later.

# Remappings for easier imports (optional but good practice)
# remappings = [
#     '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
# ]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
