"""add_project_application_table_2

Revision ID: d7784e03f8cd
Revises: a33991c30cc3
Create Date: 2025-05-17 00:43:58.741822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7784e03f8cd'
down_revision: Union[str, None] = 'a33991c30cc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', 'IN_PROGRESS', 'CANCELLED', name='applicationstatus'), nullable=False),
    sa.Column('application_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_applications_id'), 'project_applications', ['id'], unique=False)
    op.create_index(op.f('ix_project_applications_project_id'), 'project_applications', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_applications_user_id'), 'project_applications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_applications_user_id'), table_name='project_applications')
    op.drop_index(op.f('ix_project_applications_project_id'), table_name='project_applications')
    op.drop_index(op.f('ix_project_applications_id'), table_name='project_applications')
    op.drop_table('project_applications')
    # ### end Alembic commands ###
